const REPO='owca217/FPS_MMO';
const API='https://api.github.com';
const STATUSES=[['backlog','BACKLOG'],['todo','DO ZROBIENIA'],['doing','W TRAKCIE'],['testing','TESTY'],['done','GOTOWE']];
const CATEGORIES=['Gameplay','Multiplayer','Maps','Bugs','Server','UI'];
const seed=[
{id:'movement',title:'Ruch sieciowy',description:'Host i klient poruszają się poprawnie.',category:'Multiplayer',priority:'high',status:'done'},
{id:'rotation',title:'Obrót klienta',description:'Naprawione sterowanie kamerą i obrotem klienta.',category:'Multiplayer',priority:'high',status:'done'},
{id:'map-fix',title:'Zmiana mapy — separacja graczy',description:'Naprawiono błąd przenoszący drugiego gracza razem z pierwszym.',category:'Maps',priority:'critical',status:'done'},
{id:'damage',title:'HP + damage',description:'Serwer powinien autorytatywnie naliczać obrażenia i synchronizować HP.',category:'Gameplay',priority:'critical',status:'todo'},
{id:'respawn',title:'Śmierć + respawn',description:'Pełny cykl śmierci, odrodzenia i przywrócenia stanu gracza.',category:'Gameplay',priority:'high',status:'todo'},
{id:'feedback',title:'Feedback trafienia',description:'Hitmarker, otrzymane obrażenia i czytelny feedback combatowy.',category:'UI',priority:'medium',status:'todo'},
{id:'net-layer',title:'Warstwa multiplayer',description:'Dalsze porządkowanie ownership, synchronizacji i RPC.',category:'Multiplayer',priority:'high',status:'doing'},
{id:'map-flow',title:'Przejścia między mapami',description:'Rozszerzyć poprawiony system o kolejne scenariusze i testy.',category:'Maps',priority:'high',status:'doing'},
{id:'local-test',title:'Test host + client',description:'Po każdej zmianie sieciowej wykonać test dwóch instancji.',category:'Bugs',priority:'high',status:'testing'},
{id:'inventory',title:'System ekwipunku',description:'Broń, amunicja i przedmioty gracza.',category:'Gameplay',priority:'medium',status:'backlog'},
{id:'persistence',title:'Persistencja postaci',description:'Zapisywanie danych gracza między sesjami.',category:'Server',priority:'medium',status:'backlog'},
{id:'dedicated',title:'Dedicated server',description:'Deployment i infrastruktura serwera — etap odłożony na później.',category:'Server',priority:'low',status:'backlog'}
];
let tasks=loadTasks();let activeFilter='all';let token=sessionStorage.getItem('fps_mmo_gh_token')||'';
const board=document.querySelector('#board');const dialog=document.querySelector('#taskDialog');const form=document.querySelector('#taskForm');const statusInput=document.querySelector('#statusInput');const deleteBtn=document.querySelector('#deleteTaskBtn');const tokenInput=document.querySelector('#tokenInput');const syncStatus=document.querySelector('#syncStatus');
for(const [value,label] of STATUSES){const o=document.createElement('option');o.value=value;o.textContent=label;statusInput.appendChild(o)}
tokenInput.value=token;
function loadTasks(){try{const saved=JSON.parse(localStorage.getItem('fps_mmo_board_tasks'));return Array.isArray(saved)&&saved.length?saved:structuredClone(seed)}catch{return structuredClone(seed)}}
function saveTasks(){localStorage.setItem('fps_mmo_board_tasks',JSON.stringify(tasks))}
function id(){return `${Date.now()}-${Math.random().toString(16).slice(2)}`}
function priorityLabel(p){return {low:'Niski',medium:'Średni',high:'Wysoki',critical:'Krytyczny'}[p]||p}
function filtered(){return activeFilter==='all'?tasks:tasks.filter(t=>t.category===activeFilter)}
function labelsFor(t){return ['project-board',`status:${t.status}`,`category:${t.category.toLowerCase()}`,`priority:${t.priority}`]}
function parseLabels(labels){const names=labels.map(x=>typeof x==='string'?x:x.name);return {status:names.find(x=>x.startsWith('status:'))?.split(':')[1]||'backlog',category:(names.find(x=>x.startsWith('category:'))?.split(':')[1]||'Gameplay'),priority:names.find(x=>x.startsWith('priority:'))?.split(':')[1]||'medium'} }
function normalizeCategory(v){const hit=CATEGORIES.find(x=>x.toLowerCase()===String(v).toLowerCase());return hit||'Gameplay'}
async function gh(path,options={}){if(!token)throw new Error('Brak tokenu GitHub');const r=await fetch(`${API}${path}`,{...options,headers:{Accept:'application/vnd.github+json','X-GitHub-Api-Version':'2022-11-28',Authorization:`Bearer ${token}`,...(options.headers||{})}});if(!r.ok)throw new Error(`${r.status} ${await r.text()}`);return r.status===204?null:r.json()}
async function ensureLabels(){const wanted=[['project-board','0969da'],...STATUSES.map(([v])=>[`status:${v}`,'1d76db']),...CATEGORIES.map(v=>[`category:${v.toLowerCase()}`,'8250df']),...['low','medium','high','critical'].map(v=>[`priority:${v}`,'fbca04'])];let existing=[];try{existing=await gh(`/repos/${REPO}/labels?per_page=100`)}catch{return}const names=new Set(existing.map(x=>x.name));for(const [name,color] of wanted){if(!names.has(name)){try{await gh(`/repos/${REPO}/labels`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name,color})})}catch{}}}}
async function pullIssues(){syncStatus.textContent='Pobieranie z GitHub…';const issues=await gh(`/repos/${REPO}/issues?state=all&labels=project-board&per_page=100`);tasks=issues.filter(i=>!i.pull_request).map(i=>{const meta=parseLabels(i.labels);return{id:String(i.number),issueNumber:i.number,title:i.title,description:i.body||'',category:normalizeCategory(meta.category),priority:meta.priority,status:i.state==='closed'?'done':meta.status}});saveTasks();render();syncStatus.textContent=`Połączono • ${tasks.length} zadań`;}
async function createIssue(task){const issue=await gh(`/repos/${REPO}/issues`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({title:task.title,body:task.description,labels:labelsFor(task)})});task.issueNumber=issue.number;task.id=String(issue.number);return issue;}
async function updateIssue(task){if(!task.issueNumber)return createIssue(task);await gh(`/repos/${REPO}/issues/${task.issueNumber}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({title:task.title,body:task.description,state:task.status==='done'?'closed':'open',labels:labelsFor(task)})});}
async function deleteIssue(task){if(!task.issueNumber)return;await gh(`/repos/${REPO}/issues/${task.issueNumber}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({state:'closed',state_reason:'not_planned'})});}
async function syncAll(){if(!token){syncStatus.textContent='Wprowadź token GitHub';return}try{await ensureLabels();const locals=tasks.filter(t=>!t.issueNumber);for(const t of locals)await createIssue(t);saveTasks();await pullIssues()}catch(e){syncStatus.textContent=`Błąd synchronizacji: ${e.message}`}}
function render(){board.innerHTML='';const visible=filtered();for(const [status,label] of STATUSES){const col=document.createElement('section');col.className='column';const items=visible.filter(t=>t.status===status);col.innerHTML=`<div class="column-head"><span class="column-title">${label}</span><span class="count">${items.length}</span></div><div class="task-list"></div>`;const list=col.querySelector('.task-list');if(!items.length)list.innerHTML='<div class="empty">Brak zadań</div>';for(const task of items)list.appendChild(taskCard(task));board.appendChild(col)}updateStats()}
function taskCard(task){const el=document.createElement('article');el.className='task';el.dataset.id=task.id;el.innerHTML=`<div class="task-top"><h3></h3><button class="icon-btn edit" aria-label="Edytuj">⋯</button></div><p></p><div class="meta"><span class="badge category"></span><span class="badge priority-${task.priority}"></span></div><div class="move-row"><button class="move-btn prev">← Poprzedni</button><button class="move-btn next">Następny →</button></div>`;el.querySelector('h3').textContent=task.title;el.querySelector('p').textContent=task.description||'Bez opisu';el.querySelector('.category').textContent=task.category;el.querySelector(`.priority-${task.priority}`).textContent=`Priorytet: ${priorityLabel(task.priority)}`;el.querySelector('.edit').onclick=()=>openEdit(task.id);el.querySelector('.prev').onclick=()=>move(task.id,-1);el.querySelector('.next').onclick=()=>move(task.id,1);const idx=STATUSES.findIndex(x=>x[0]===task.status);el.querySelector('.prev').disabled=idx<=0;el.querySelector('.next').disabled=idx>=STATUSES.length-1;return el}
async function move(taskId,dir){const task=tasks.find(t=>t.id===taskId);const idx=STATUSES.findIndex(x=>x[0]===task.status);const next=STATUSES[idx+dir];if(!task||!next)return;task.status=next[0];saveTasks();render();if(token){try{await updateIssue(task);syncStatus.textContent='Zapisano w GitHub'}catch(e){syncStatus.textContent=`Błąd zapisu: ${e.message}`}}}
function updateStats(){document.querySelector('#totalCount').textContent=tasks.length;document.querySelector('#doingCount').textContent=tasks.filter(t=>t.status==='doing').length;document.querySelector('#testingCount').textContent=tasks.filter(t=>t.status==='testing').length;document.querySelector('#doneCount').textContent=tasks.filter(t=>t.status==='done').length}
function openNew(){form.reset();document.querySelector('#taskId').value='';document.querySelector('#dialogTitle').textContent='Nowe zadanie';statusInput.value='backlog';deleteBtn.classList.add('hidden');dialog.showModal()}
function openEdit(taskId){const t=tasks.find(x=>x.id===taskId);if(!t)return;document.querySelector('#taskId').value=t.id;document.querySelector('#titleInput').value=t.title;document.querySelector('#descriptionInput').value=t.description;document.querySelector('#categoryInput').value=t.category;document.querySelector('#priorityInput').value=t.priority;statusInput.value=t.status;document.querySelector('#dialogTitle').textContent='Edytuj zadanie';deleteBtn.classList.remove('hidden');dialog.showModal()}
function close(){dialog.close()}
document.querySelector('#connectBtn').onclick=async()=>{token=tokenInput.value.trim();if(token){sessionStorage.setItem('fps_mmo_gh_token',token);await syncAll()}else{sessionStorage.removeItem('fps_mmo_gh_token');syncStatus.textContent='Tryb lokalny'}};
document.querySelector('#syncBtn').onclick=syncAll;
document.querySelector('#addTaskBtn').onclick=openNew;document.querySelector('#closeDialogBtn').onclick=close;document.querySelector('#cancelBtn').onclick=close;
form.addEventListener('submit',async e=>{e.preventDefault();const data={title:document.querySelector('#titleInput').value.trim(),description:document.querySelector('#descriptionInput').value.trim(),category:document.querySelector('#categoryInput').value,priority:document.querySelector('#priorityInput').value,status:statusInput.value};if(!data.title)return;const taskId=document.querySelector('#taskId').value;let task;if(taskId){task=tasks.find(t=>t.id===taskId);Object.assign(task,data)}else{task={id:id(),...data};tasks.push(task)}saveTasks();close();render();if(token){try{await updateIssue(task);saveTasks();syncStatus.textContent='Zapisano w GitHub'}catch(e){syncStatus.textContent=`Błąd zapisu: ${e.message}`}}});
deleteBtn.onclick=async()=>{const taskId=document.querySelector('#taskId').value;if(!taskId)return;if(confirm('Usunąć to zadanie?')){const task=tasks.find(t=>t.id===taskId);if(token&&task){try{await deleteIssue(task)}catch(e){syncStatus.textContent=`Błąd GitHub: ${e.message}`}}tasks=tasks.filter(t=>t.id!==taskId);saveTasks();close();render()}};
document.querySelectorAll('.filter').forEach(btn=>btn.onclick=()=>{document.querySelectorAll('.filter').forEach(b=>b.classList.remove('active'));btn.classList.add('active');activeFilter=btn.dataset.filter;render()});
render();if(token)syncAll();
